name: api_test
description: Test script for Speech Recognition API

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  http: ^1.1.0
  web_socket_channel: ^2.4.0
  record: ^4.4.4
  path_provider: ^2.1.1 