services:
  - type: web
    name: speech-recognition-api
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PICOVOICE_ACCESS_KEY
        sync: false # This will prompt you to enter it securely in Render dashboard
      - key: PROFILES_DIR
        value: /data/profiles
      - key: PORT
        value: 10000
    healthCheckPath: /health
    healthCheckTimeout: 30
    autoDeploy: true
    disk:
      name: profiles
      mountPath: /data/profiles
      sizeGB: 1
    scaling:
      minInstances: 1
      maxInstances: 1
      targetMemoryPercent: 80
    routes:
      - type: rewrite
        source: /*
        destination: /*
        websocket: true