services:
  - type: web
    name: speech-recognition-api
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PICOVOICE_ACCESS_KEY
        sync: false # This will prompt you to enter it securely in Render dashboard
      - key: PROFILES_DIR
        value: ./profiles
    healthCheckPath: /speakers
    buildCommand: docker build -t speech-recognition-api .
    startCommand: docker run -p 8000:8000 speech-recognition-api
    disk:
      name: profiles
      mountPath: /data/profiles
      sizeGB: 1