services:
  - type: web
    name: speech-recognition-api
    env: docker
    plan: free
    envVars:
      - key: PICOVOICE_ACCESS_KEY
        sync: false # This will prompt you to enter it securely in Render dashboard
      - key: PROFILES_DIR
        value: /data/profiles
    disk:
      name: profiles
      mountPath: /data/profiles
      sizeGB: 1