services:
  - type: web
    name: speech-recognition-api
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PICOVOICE_ACCESS_KEY
        sync: false
      - key: PROFILES_DIR
        value: /data/profiles
      - key: PORT
        value: 10000
      - key: WEB_CONCURRENCY
        value: "1"
      - key: WORKER_MAX_REQUESTS
        value: "500"
      - key: WORKER_MAX_REQUESTS_JITTER
        value: "50"
    healthCheckPath: /health
    healthCheckTimeout: 30
    autoDeploy: true
    disk:
      name: profiles
      mountPath: /data/profiles
      sizeGB: 1
    scaling:
      minInstances: 1
      maxInstances: 1
      targetMemoryPercent: 85
      targetCPUPercent: 85
    plan: standard
    resources:
      memory: 2048
      cpu: 1
    routes:
      - type: rewrite
        source: /*
        destination: /*
        websocket: true